-- Unmap builtin keybindings that I don't use.  This is a lot of them.  Keys are unbound because:
--
--   - I haven't found them useful
--   - I use a different workflow to achieve the same functionality
--   - I have an easier to remember mapping defined in mappings.lua

local normal_mode = {
    "<CTRL-A>",
    "<CTRL-B>",
    "<CTRL-E>",
    "<CTRL-F>",
    "<CTRL-G>",
    "<BS>",
    "<CTRL-H>",
    "<Tab>",
    "<CTRL-I>",
    "<NL>",
    "<CTRL-J>",
    "<CTRL-M>",
    "<CTRL-N>",
    "<CTRL-O>",
    "<CTRL-P>",
    "<CTRL-R>",
    "<CTRL-T>",
    "<CTRL-W>",
    "<CTRL-X>",
    "<CTRL-Y>",
    "<CTRL-]>",
    "<CTRL-^>",
    "<CTRL-Tab>",
    "<Space>",
    "!",
    "#",
    "%",
    "&",
    "'",
    "*",
    "+",
    ",",
    "-",
    "<",
    ">",
    "=",
    "[",
    "]",
    "z",
    "g",
    "Q",
    "Z",
    "G",
    "`",
    "do",
    "dp",
    "q:",
    "q/",
    "q?",
    "{",
    "|",
    "}",
    "~",
    "<C-End>",
    "<C-Home>",
    "<C-Left>",
    "<C-LeftMouse>",
    "<C-Right>",
    "<C-RightMouse>",
    "<End>",
    "<F1>",
    "<Help>",
    "<Home>",
    "<Insert>",
    "<LeftMouse>",
    "<MiddleMouse>",
    "<PageDown>",
    "<PageUp>",
    "<RightMouse>",
    "<S-Down>",
    "<S-Left>",
    "<S-LeftMouse>",
    "<S-Right>",
    "<S-RightMouse>",
    "<S-Up>",
    "<Undo>",
}

for index,key in pairs(normal_mode)
do
    vim.api.nvim_set_keymap("n", key, "<nop>", {
	nowait=true,
	noremap=true,
    })
end
